import { MfoBrand } from "../types";

export const initialMfoBrands: MfoBrand[] = [
  {
    id: "zaimer",
    name: "Займер",
    rating: 4.9,
    maxAmount: 30000,
    minAmount: 2000,
    dailyRate: 0.8,
    minTerm: 7,
    maxTerm: 30,
    approvalRate: 98,
    ageMin: 18,
    ageMax: 75,
    documents: ["Паспорт РФ"],
    cbLicense: "№ 6130142003827",
    cbDate: "11.10.2013",
    partnerUrl: "https://partner.zaimer.ru/click?offer_id=1&aff_id=100",
    logoColor: "from-amber-500 to-orange-600",
    logoText: "ЗМ",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "ЮMoney", "СБП", "Qiwi"],
    isActive: true,
    features: ["Робот займов", "Одобрение за 2 мин", "Без звонков"],
    seoDescription: "Робот онлайн-займов Займер осуществляет полностью автоматическое рассмотрение заявок без выходных и праздников. Одобрение до 98% за счет уникального кредитного скоринга."
  },
  {
    id: "ekapusta",
    name: "еКапуста",
    rating: 4.8,
    maxAmount: 30000,
    minAmount: 1000,
    dailyRate: 0.8,
    minTerm: 7,
    maxTerm: 21,
    approvalRate: 97,
    ageMin: 18,
    ageMax: 70,
    documents: ["Паспорт РФ"],
    cbLicense: "№ 2120754001243",
    cbDate: "22.03.2012",
    partnerUrl: "https://ekapusta.com/click?aff=200",
    logoColor: "from-green-500 to-emerald-700",
    logoText: "еК",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "ЮMoney", "СБП", "QIWI", "Золотая Корона"],
    isActive: true,
    features: ["Первый займ 0%", "Мгновенно", "Круглосуточно 24/7"],
    seoDescription: "Популярный сервис мгновенных онлайн-займов. Известен высоким уровнем лояльности к заемщикам с любой кредитной историей и бережным отношением к клиентам."
  },
  {
    id: "moneyman",
    name: "MoneyMan",
    rating: 4.9,
    maxAmount: 80000,
    minAmount: 1500,
    dailyRate: 0.8,
    minTerm: 5,
    maxTerm: 90, // supports long term loans too!
    approvalRate: 95,
    ageMin: 20,
    ageMax: 70,
    documents: ["Паспорт РФ", "СНИЛС"],
    cbLicense: "№ 2110177000478",
    cbDate: "25.10.2011",
    partnerUrl: "https://moneyman.ru/leads?ref=300",
    logoColor: "from-lime-500 to-green-600",
    logoText: "ММ",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "Банковский счет", "СБП"],
    isActive: true,
    features: ["Суммы до 80 000 ₽", "Низкие ставки", "Без залога"],
    seoDescription: "Один из лидеров рынка микрофинансирования в РФ. Предлагает гибкую сетку тарифов от краткосрочных займов 'до зарплаты' до крупных долгосрочных ссуд."
  },
  {
    id: "webzaim",
    name: "Веб-займ",
    rating: 4.7,
    maxAmount: 30000,
    minAmount: 3000,
    dailyRate: 0.8,
    minTerm: 7,
    maxTerm: 30,
    approvalRate: 94,
    ageMin: 18,
    ageMax: 65,
    documents: ["Паспорт РФ"],
    cbLicense: "№ 2190354009316",
    cbDate: "13.06.2019",
    partnerUrl: "https://web-zaim.ru/track?click_id=400",
    logoColor: "from-blue-500 to-indigo-600",
    logoText: "ВЗ",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "Банковский счет"],
    isActive: true,
    features: ["Акция для новых клиентов", "Программа привилегий"],
    seoDescription: "Онлайн-сервис выдачи займов. Предлагает выгодную программу лояльности Снижайка, позволяющую постоянным клиентам уменьшать процентную ставку до 0.5% в день."
  },
  {
    id: "lime",
    name: "Лайм-Займ",
    rating: 4.6,
    maxAmount: 70000,
    minAmount: 2000,
    dailyRate: 0.8,
    minTerm: 10,
    maxTerm: 168, // long-term
    approvalRate: 92,
    ageMin: 21,
    ageMax: 70,
    documents: ["Паспорт РФ", "СНИЛС", "ИНН"],
    cbLicense: "№ 6513035500039",
    cbDate: "17.10.2013",
    partnerUrl: "https://lime-zaim.ru?aff_id=500",
    logoColor: "from-teal-400 to-emerald-600",
    logoText: "ЛЗ",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "ЮMoney", "СБП", "QIWI"],
    isActive: true,
    features: ["Долгосрочные займы", "Промокоды на скидку", "Быстрый перевод"],
    seoDescription: "Технологичная МФК, предоставляющая займы на любые сроки. Удобный личный кабинет и лояльные условия оценки платежеспособности для самозанятых."
  },
  {
    id: "dobrozaim",
    name: "Доброзайм",
    rating: 4.7,
    maxAmount: 100000, // Large amount!
    minAmount: 1000,
    dailyRate: 0.7, // Lower rate for long term
    minTerm: 1,
    maxTerm: 365, // Long term!
    approvalRate: 91,
    ageMin: 19,
    ageMax: 90, // Elderly allowed!
    documents: ["Паспорт РФ"],
    cbLicense: "№ 2110177000540",
    cbDate: "03.11.2011",
    partnerUrl: "https://dobrozaim.ru/partner?click=600",
    logoColor: "from-rose-500 to-red-700",
    logoText: "ДЗ",
    isFirstPromoZero: false,
    payoutMethods: ["Карта", "Наличные в офисе", "СБП"],
    isActive: true,
    features: ["До 100 000 ₽", "Пенсионерам скидка", "Физические офисы"],
    seoDescription: "Крупная компания с развитой филиальной сетью. Специализируется на долгосрочных займах для граждан, включая пенсионеров до 90 лет и студентов."
  },
  {
    id: "bystrodengi",
    name: "Быстроденьги",
    rating: 4.5,
    maxAmount: 100000,
    minAmount: 1000,
    dailyRate: 0.8,
    minTerm: 7,
    maxTerm: 180,
    approvalRate: 96,
    ageMin: 18,
    ageMax: 75,
    documents: ["Паспорт РФ"],
    cbLicense: "№ 2110573000002",
    cbDate: "08.07.2011",
    partnerUrl: "https://bystrodengi.ru/?ref=700",
    logoColor: "from-sky-500 to-blue-700",
    logoText: "БД",
    isFirstPromoZero: true,
    payoutMethods: ["Карта", "Расчетный счет", "Быстрокарта"],
    isActive: true,
    features: ["Моментальная СБП", "Грейс-период", "Доступно с 18 лет"],
    seoDescription: "Один из старейших брендов микрофинансового сектора в России. Выдача средств производится онлайн на банковские карты или наличными в кратчайшие сроки."
  },
  {
    id: "turbozaim",
    name: "Турбозайм",
    rating: 4.6,
    maxAmount: 50000,
    minAmount: 3000,
    dailyRate: 0.8,
    minTerm: 7,
    maxTerm: 30,
    approvalRate: 93,
    ageMin: 21,
    ageMax: 65,
    documents: ["Паспорт РФ", "СНИЛС"],
    cbLicense: "№ 6513032600035",
    cbDate: "29.08.2013",
    partnerUrl: "https://turbozaim.ru/?aff=800",
    logoColor: "from-purple-500 to-indigo-700",
    logoText: "ТЗ",
    isFirstPromoZero: false,
    payoutMethods: ["Карта", "ЮMoney"],
    isActive: true,
    features: ["Решение за 1 минуту", "Интеграция с Госуслугами"],
    seoDescription: "Удобный и быстрый онлайн сервис, интегрированный с порталом Госуслуг для упрощенной регистрации и мгновенного прохождения идентификации личности."
  }
];
